# Generated by Django 4.2.1 on 2023-05-30 06:13

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("block_no", models.CharField(default="", max_length=50)),
                ("lot_no", models.CharField(default="", max_length=50)),
                ("phase", models.CharField(default="", max_length=50)),
                ("area", models.CharField(default="", max_length=50)),
                ("capacity", models.PositiveIntegerField()),
                ("lat1", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("long1", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("lat2", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("long2", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("lat3", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("long3", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("lat4", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("long4", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "transaction_no",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("corpse_last_name", models.CharField(default="", max_length=100)),
                ("corpse_first_name", models.CharField(default="", max_length=100)),
                ("date_reserved", models.DateField(default=django.utils.timezone.now)),
                (
                    "slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.lot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Corpse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(default="", max_length=100)),
                ("first_name", models.CharField(default="", max_length=100)),
                (
                    "slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.lot",
                    ),
                ),
            ],
        ),
    ]
