# Generated by Django 4.2.1 on 2023-05-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_name_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="block_no",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="reservation",
            name="lot_no",
            field=models.CharField(default="", max_length=100),
        ),
    ]
