# Generated by Django 4.2.1 on 2023-05-31 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_lat1_lot_lat_long1_rename_lat2_lot_lat_long2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="slot",
            new_name="Lot_Id",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="block_no",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="lot_no",
        ),
    ]
