# Generated by Django 4.2.1 on 2023-05-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_lot_id_reservation_lot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="user",
            new_name="User",
        ),
    ]
