# Generated by Django 4.2.1 on 2023-06-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_rename_user_reservation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="salt",
            field=models.CharField(default="", max_length=255),
        ),
    ]
