# Generated by Django 4.2.1 on 2023-06-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_customuser_salt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="salt",
        ),
    ]
