# Generated by Django 4.2.1 on 2023-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_customuser_salt"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="salt",
            field=models.CharField(default="", max_length=255),
        ),
    ]
